cabal-version:      3.0
name:               dosh
version:            24.6
synopsis:           The power of Haskell in your terminal!
homepage:           https://github.com/ners/dosh
license:            Apache-2.0
license-file:       LICENCE.md
author:             ners
maintainer:         ners@gmx.ch
category:           System
build-type:         Simple

common common
    default-language: GHC2021
    ghc-options:
        -Weverything
        -Wno-unsafe
        -Wno-missing-safe-haskell-mode
        -Wno-missing-export-lists
        -Wno-missing-import-lists
        -Wno-missing-kind-signatures
        -Wno-all-missed-specialisations
    default-extensions:
        ApplicativeDo
        Arrows
        BlockArguments
        DataKinds
        DefaultSignatures
        DeriveAnyClass
        DeriveGeneric
        DerivingStrategies
        DerivingVia
        ExplicitNamespaces
        LambdaCase
        NoFieldSelectors
        NoImplicitPrelude
        OverloadedLabels
        OverloadedRecordDot
        OverloadedStrings
        PackageImports
        RecordWildCards
        RecursiveDo
        StrictData
        TypeFamilies
        ViewPatterns
    build-depends:
        dosh-prelude,

library
    import:           common
    hs-source-dirs:   src
    exposed-modules:
        Dosh.App,
        Dosh.LSP.DiagnosticsClock,
        Dosh.LSP.SemanticTokensClock,
        Dosh.LSP.Session,
        Dosh.Program,
        Dosh.Widgets.CodeInput,
    other-modules:
        Data.Position,
        Data.Integral,
        Prelude,
        System.Terminal.Extra,
    build-depends:
        aeson,
        automaton,
        base,
        bytestring,
        co-log-core,
        containers,
        data-default,
        data-interval,
        exceptions,
        extended-reals,
        extra,
        generic-lens,
        ghcide,
        haskell-language-server,
        hie-bios,
        hls-plugin-api,
        lens,
        lsp,
        lsp-client,
        lsp-types,
        monad-schedule,
        mtl,
        prettyprinter,
        rhine,
        rhine-terminal,
        row-types,
        stm,
        terminal,
        terminal-widgets,
        text,
        text-rope,
        text-rope-zipper,
        transformers,
        unordered-containers,

executable dosh
    import:           common
    main-is:          Main.hs
    hs-source-dirs:   app
    ghc-options:
        -threaded
    build-depends:
        dosh,
