name: Continuous integration
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  build:
    strategy:
      matrix:
        target: ['default', 'ghc94.dosh']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
    - uses: cachix/cachix-action@v12
      with:
        name: dosh
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#${{ matrix.target }}
